name: Publish Package to npmjs
on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile

      - name: Pack package
        working-directory: ./packages/tiptap-link-card
        run: bun pm pack --filename tiptap-link-card.tgz

      - name: Publish to npm
        working-directory: ./packages/tiptap-link-card
        run: bun publish --access public ./tiptap-link-card.tgz
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          files: ./packages/tiptap-link-card/tiptap-link-card.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
